// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mazzgwqbycwkphdmoubs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1henpnd3FieWN3a3BoZG1vdWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODE5NzAsImV4cCI6MjA1OTk1Nzk3MH0.ca2Na4_kg9NW7czYCp8I8789my00aOfbs9YhonxetZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);